Handle 'wlr_seat_get_keyboard' possibly returning null.
djpohly/dwl pull request #230
Opened 2022-05-02 16:09 UTC by BenJarg

I've gotten segfaults with certain uses of wtype because of dwl not checking if wlr_seat_get_keyboard returns NULL (looks like others also had this issue, see #124 ). This solution handles this case the same way sway handles this.

2022-05-08 22:58 UTC, Sevz17 requested changes

2022-05-08 22:58 UTC, Sevz17 commented on dwl.c
> +				else wlr_seat_keyboard_notify_enter(seat, layersurface->layer_surface->surface, NULL, 0, NULL);
```suggestion
				if (kb)
					wlr_seat_keyboard_notify_enter(seat, layersurface->layer_surface->surface,
							kb->keycodes, kb->num_keycodes, &kb->modifiers);
				else
					wlr_seat_keyboard_notify_enter(seat, layersurface->layer_surface->surface, NULL, 0, NULL);
```

2022-05-08 22:58 UTC, Sevz17 commented on dwl.c
> +	else wlr_seat_keyboard_notify_enter(seat, client_surface(c), NULL, 0, NULL);
```suggestion
	if (kb)
		wlr_seat_keyboard_notify_enter(seat, client_surface(c),
				kb->keycodes, kb->num_keycodes, &kb->modifiers);
	else
		wlr_seat_keyboard_notify_enter(seat, client_surface(c), NULL, 0, NULL);
```

2022-05-09 14:04 UTC, Sevz17 commented
Does this close #124?

2022-05-09 14:44 UTC, BenJarg commented
Yes, I believe it does.

2022-05-09 18:18 UTC, merged

2022-05-09 18:18 UTC, Sevz17 commented
Thanks!