Updated makedesktop patch
djpohly/dwl pull request #484
Opened 2023-09-21 13:20 UTC by weiseguy1

Updated the original makeDesktop patch

2023-09-21 14:05 UTC, pm4rcin commented
@sevz17 I'm wondering if it couldn't be merged since it doesn't increase SLOC in dwl.c nor any header files and is just a few lines in Makefile. Also it just makes things easier if someone uses login manager since it's automatically discoverable. It doesn't alter the behaviour of dwl but it's just QOL improvement for people that need it.

2023-09-22 01:42 UTC, sevz17 commented
> @sevz17 I'm wondering if it couldn't be merged since it doesn't increase SLOC in dwl.c nor any header files and is just a few lines in Makefile. Also it just makes things easier if someone uses login manager since it's automatically discoverable. It doesn't alter the behaviour of dwl but it's just QOL improvement for people that need it.

Well, dwm doesn't include it so neither do we, but meh, let's do it.

Also do note that just like sway we don't support login managers (I know, it's not mentioned anywhere, I want add it and more documentation but I haven't had time)

2023-09-22 01:49 UTC, weiseguy1 commented
Not gonna lie, this is pretty cool considering this is my first pull request to a major project!

2023-09-22 01:57 UTC, sevz17 requested changes

2023-09-22 01:57 UTC, sevz17 commented on Makefile
> +	cp -f dwl.desktop $(DESKTOP)/dwl.desktop
This should be copied to `$(DESTDIR)$(PREFIX)/share/wayland-sessions/dwl.desktop`

2023-09-22 01:57 UTC, sevz17 commented on dwl.desktop
> +Name=DWL
lowercase please.

2023-09-22 01:57 UTC, sevz17 commented on dwl.desktop
> +Exec=/usr/local/bin/dwl
Just use `dwl`

2023-09-22 03:59 UTC, sevz17 commented on dwl.desktop
> +Exec=/usr/local/bin/dwl
Err... I meant just replace `/usr/local/bin/dwl` with `dwl`, sorry for the ambiguity

2023-09-22 08:01 UTC, pm4rcin commented on dwl.desktop
> +Comment=dwl for Wayland
Change it back as it is `dwm for Wayland`.

2023-09-22 11:38 UTC, pm4rcin commented
One last thing to do. Squash the commits into one and that's it from my perspective.

2023-09-22 11:51 UTC, weiseguy1 commented
done

2023-09-22 12:23 UTC, pm4rcin commented
Give that commit sensible name like `Add desktop entry file` or something similar. Also change the PR name since it's meaning has changed.

2023-09-22 13:23 UTC, sevz17 commented
Please `s/Added/add/` in the commit message

2023-09-23 01:49 UTC, merged

2023-09-23 01:49 UTC, sevz17 commented
Thank you!